"""Plugin scaffold generator (spec: PLUGIN ARCHITECTURE).

``ksec plugin new`` creates a ready-to-fill plugin directory: manifest.json
with the declared permissions/capability, an adapter module following the
ToolAdapter contract, a parser module and a README. The generated plugin
validates out of the box (``ksec plugin check``) so a developer can start
from a working skeleton instead of a blank folder.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ksec.core.errors import KSECError
from ksec.plugins.manifest import CATEGORIES, PERMISSIONS, SAFETY_CLASSES, TRUST_LEVELS

_ADAPTER_TEMPLATE = '''\"\"\"Adapter for the {name} capability (generated by ``ksec plugin new``).

Executes the configured binary and hands its output to the default parser.
Replace the placeholder command with the real tool invocation.
\"\"\"
from __future__ import annotations

from ksec.adapters.base import ToolAdapter


class {class_name}(ToolAdapter):
    """Runs {tool} against an authorized target."""

    # Binary invoked on the system; may be overridden by ``ksec tools install``.
    name = "{tool}"
    capability = "{capability}"
    # Safety class drives the permissions required by the manifest:
    # PASSIVE | ACTIVE_SAFE | ACTIVE_AGGRESSIVE
    safety = "{safety}"

    def build_command(self, target: str, options: dict | None = None) -> list[str]:
        return [self.name, target]

    def parse_output(self, output: str):
        """Let the default parser interpret the raw output."""
        return super().parse_output(output)
'''

_PARSER_TEMPLATE = '''\"\"\"Parser for {tool} output (generated by ``ksec plugin new``).

The default parser stores raw output as evidence and extracts entities. For
structured findings, implement :meth:`parse` and return entity/finding
records — see ``ksec/parsers/base.py`` and the built-in parsers in
``ksec/parsers/`` for the contract.
\"\"\"
from __future__ import annotations

from ksec.parsers.base import OutputParser


class {class_name}(OutputParser):
    name = "{capability}"

    def parse(self, output: str) -> dict:
        # Replace with real extraction; the base class always records raw
        # evidence so a job never silently loses output.
        return super().parse(output)
'''

_MANIFEST_TEMPLATE = """{{
  "id": "{plugin_id}",
  "name": "{display_name}",
  "version": "0.1.0",
  "description": "{description}",
  "author": "{author}",
  "category": "{category}",
  "trust_level": "{trust_level}",
  "safety": "{safety}",
  "permissions": {permissions},
  "capabilities": ["{capability}"],
  "dependencies": {{"tools": ["{tool}"]}},
  "adapters": [
    {{
      "capability": "{capability}",
      "tool": "{tool}",
      "safety": "{safety}",
      "parser": "{capability}",
      "module": "adapter",
      "class": "{class_name}"
    }}
  ],
  "parsers": [
    {{
      "name": "{capability}",
      "module": "parser",
      "class": "{parser_class}"
    }}
  ]
}}
"""

_README_TEMPLATE = """# {display_name}

Generated by ``ksec plugin new``. Fill in the placeholder logic, then:

```bash
ksec plugin install {path} --trust {trust_level} --user admin --password '...' --yes
ksec plugin check
ksec tools list          # capability registered?
ksec ask "{capability}"   # mentor card (after adding the topic)
```

## Manifest

* id: `{plugin_id}`
* capability: `{capability}`
* permissions: {permissions} (validated against the fixed permission set)
* trust level: `{trust_level}`

Edit `manifest.json`, `adapter.py` and `parser.py` — then re-run
`ksec plugin install` for the changes to take effect.
"""

_ID_RE = re.compile(r"^[a-z0-9][a-z0-9_.-]*$")


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")


def scaffold_plugin(
    name: str,
    *,
    target_dir: Path,
    capability: str = "",
    tool: str = "",
    category: str = "other",
    description: str = "",
    author: str = "",
    safety: str = "ACTIVE_SAFE",
    trust_level: str = "LOCAL",
) -> Path:
    """Create a plugin skeleton at ``target_dir`` and return its path."""
    plugin_id = _slug(name)
    if not _ID_RE.fullmatch(plugin_id):
        raise KSECError(
            f"plugin id must be a lowercase dotted identifier, got {name!r}"
        )
    # Adapter registry keys use underscores (port_scan, dns_enum, ...), so
    # normalize the capability id to match core convention.
    capability = (capability or plugin_id).strip().lower().replace("-", "_")
    if not _ID_RE.fullmatch(capability):
        raise KSECError(
            f"capability must be a lowercase identifier, got {capability!r}"
        )
    if category not in CATEGORIES:
        raise KSECError(
            f"category must be one of {', '.join(CATEGORIES)}"
        )
    if safety not in SAFETY_CLASSES:
        raise KSECError(f"safety must be one of {', '.join(SAFETY_CLASSES)}")
    if trust_level not in TRUST_LEVELS:
        raise KSECError(f"trust_level must be one of {', '.join(TRUST_LEVELS)}")

    # SAFETY_PERMISSION_MAP is intentionally not imported: keep the manifest
    # explicit so the developer decides; the loader re-validates anyway.
    permissions: list[str] = ["network.access", "tool.execute"]
    if safety == "PASSIVE":
        permissions = ["network.access", "filesystem.read"]
    elif safety == "ACTIVE_AGGRESSIVE":
        permissions = ["network.access", "tool.execute", "network.listen"]

    tool = (tool or capability).strip()
    root = (target_dir / plugin_id).resolve()
    root.parent.mkdir(parents=True, exist_ok=True)
    if root.exists():
        raise KSECError(f"directory already exists: {root}")

    def _camel(name: str) -> str:
        return "".join(part.capitalize() for part in re.split(r"[-_]", name) if part)

    class_name = _camel(capability) + "Adapter"
    parser_class = _camel(capability) + "Parser"
    display = " ".join(part.capitalize() for part in capability.split("-"))

    files = {
        "manifest.json": _MANIFEST_TEMPLATE.format(
            plugin_id=plugin_id,
            display_name=display,
            description=description or f"{display} capability",
            author=author or "KSEC user",
            category=category,
            trust_level=trust_level,
            safety=safety,
            permissions=json.dumps(permissions),
            capability=capability,
            tool=tool,
            class_name=class_name,
            parser_class=parser_class,
        ),
        "adapter.py": _ADAPTER_TEMPLATE.format(
            name=capability, class_name=class_name,
            tool=tool, capability=capability, safety=safety,
        ),
        "parser.py": _PARSER_TEMPLATE.format(
            tool=tool, class_name=parser_class, capability=capability,
        ),
        "README.md": _README_TEMPLATE.format(
            display_name=display, path=root, trust_level=trust_level,
            plugin_id=plugin_id, capability=capability,
            permissions=", ".join(permissions),
        ),
    }
    root.mkdir()
    for filename, content in files.items():
        (root / filename).write_text(content.lstrip("\n"), encoding="utf-8")
    return root
